### ISSUE TITLE
Scrolling issue in Mobile View while navigation menu is opened

### ISSUE THREAD

**Issue by gaurav-js-dev** [jonasschmedtmann/html-css-course#2]
https://user-images.githubusercontent.com/23628920/126806761-6e22fd89-b1ec-4350-b7ca-a4fdea5bbe13.mp4

I am still able to scroll after opening the burger menu in mobile view (small screen) and it also creates weird effect in background. Please refer to the attached video for working proof of concept.

**Comment by AayushKarna** [comment]
Instead of using `position: absolute` use `position: fixed` in the the selector `.nav-open .main-nav`. Basically it gets positioned the same way as absolute position does but it remains in fixed position no matter the scroll, so that you won't get that small gap at the bottom, it will always be taking 100vh. I find it really unusual when being able to scroll background when the navigation is active, you can use some javascript and css to prevent scrolling when navigation is open.

**Comment by Alvimm** [comment]
With a big help, i have fixed this in: 14445692c85cedefa0aa82b7afbe782452a6d44f

**Comment by Alvimm** [comment]
### With a big help, i have fixed this in: https://github.com/Alvimm/Omnifood/commit/14445692c85cedefa0aa82b7afbe782452a6d44f


just ignore the "index.html" changes

> Proof.mp4 
> I am still able to scroll after opening the burger menu in mobile view (small screen) and it also creates weird effect in background. Please refer to the attached video for working proof of concept.
